### ISSUE TITLE
Community Goal: 100 Stars

### ISSUE THREAD

**Issue by luiscarbonell** [liquidcarrot/carrot#13]
## 🙏 🌟 🙏 Please Star 
>Contributors to this repo value their worth as human beings by the number of stars this repo receives.

Please give our repo one shooting star.

**Comment by wagenaartje** [comment]
Hi, I don't visit Github that often anymore but I was very pleased to see that a new spin-off of Neataptic was created the last time I looked. Compared to the others attempted to do so, you are doing an incredibly great job at documenting your library and fixing the issues that Neataptic has since it is unmaintained - something that I have wanted for a long time, therefore I have :star:ed you repository.

However, after looking at the code you have written so far I must say that next to the documentation making the code more systematic, and bug fixes, I do not see any _technical_ innovation compared to Neataptic (yet). When looking at the documentation and examples, I see _nothing_ new (but I am not so keen on JS anymore). 

Since I started this way from Synaptic, I don't find this that much of a problem - however it does bother me that you have a whole [shop](https://liquid-carrot.myshopify.com/) selling stuff that is related to your repository while it basically offers nothing new so far. I just kind of have the feeling that Carrot is used to make money of what I have created some years ago.

I wish you good luck with Carrot, but make sure to include new features that are not in Neataptic soon. Once this is the case, i'll definitely link Neataptic's readme to Carrot :wink:

**Comment by luiscarbonell** [comment]
Hey @wagenaartje thank you for the star and the support thus far! 😊 It means a lot man! 

Though we do want to create amazing documentation and tutorials, we are definitely SUPER excited to start adding some great new features to the repo - particularly "GPU acceleration", "distributed network training (e.g. Carrot + Docker)", more API _stuff_ (i.e. GANs, CapsuleNetworks, Other Cost/Activation Functions, Gym Environments, etc.). 
 
I think you built a great library 👊  - I was really enjoying using it; was sad to it go unmaintained. 

The store was really built to try and get some of the local South Florida community excited and communicating about AI. There are a ton of companies down here that would benefit greatly from AI, want AI developers, but don't want to pay the talent well enough because they are not familiar with the "value-proposition" of AI. We've been lucky enough to get a lot of support from the local universities here, but students have not been as lucky - most students in South Florida have marketing, sales, communications, etc. backgrounds but are excited about working with/on AI (in)directly. 

Our goal with the shop was to try and help give these guys a medium which they can use to get "comfortable" with AI using their natural skill-sets and talent and help pour some money into our community and contributors, events, etc. It was actually not built by @christianechevarria or I, so #ThankYou [@nicolares](https://github.com/nicolares20). 

We hope in a couple of months we can create some really great stuff (i.e. demos, features, etc.) 

Thank for the good wishes! 😄 🙇 We definitely want to keep making better and easier - will definitely let you know as we add significant new features.. It's awesome to have you watching the repo and helping guide it. 👍 👍

**Comment by D-Nice** [comment]
Nice to see @wagenaartje chiming in whom I respect and very much appreciate for the neataptic framework. I've been through a bunch of frameworks, including those considered "top dog", but even with some of its quirks and bugs, neataptic's models tended to surpass others in my hobbyist AI explorations.

I'll be an optimist here, and will commend the new contribuotors for focusing on solidifying the codebase and documenting. I'm less interested in new features, and moreso on that personally, really making it mature (albeit the top feature without a doubt for me would be some acceleration via GPUs or the like, which was really the biggest weakness of neataptic, even initially being just single-threaded, but of course moreso a nodejs challenge in general).

Good luck on this, very happy to see neataptic back in the form of carrot, I think for anyone that actually dives into this framework, they'll soon understand its value proposition...

**Comment by luiscarbonell** [comment]
@D-Nice Thank you so much for the love! 

We're glad/honored to carry the mantle!

@christianechevarria and I have been - and will continue to, focus on building great documentation, examples, cleaning up bugs, improving performance (i.e. GPU acceleration), and adding amazing new features (e.g. GANs, CapsuleNetworks, DQN & other RL, HyperNEAT Implementation, etc.).

Super glad to have you join this fledgling, but lovely community! ❤️ 👊 

P.S: Great project with [ProtonMail](https://protonmail.com/)! I've been looking for a great open-source mail client for quite some time; it's awesome to see you're building one.

**Comment by dan-ryan** [comment]
Good job with the 100 stars!

**Comment by christianechevarria** [comment]
Thank you Dan! Thanks for being a part of this community and making the project awesome 🚀
