### ISSUE TITLE
https://liquidcarrot.io/carrot/ website gives 404

### ISSUE THREAD

**Issue by theWebalyst** [liquidcarrot/carrot#238]
I'm getting a not found error accessing https://liquidcarrot.io/carrot/ and can't find an issue for this, so this can be a placeholder for how to fix etc.

I found the following links from the README work:
- https://liquidcarrot.io/
- https://liquidcarrot.io/example.flappy-bird/

This one gives a 404, but appears in the title of the repo, and elsewhere (e.g. for the Docs):
- https://liquidcarrot.io/carrot

**Comment by raimannma** [comment]
until this is fixed you could see the docs for the typescript version here: https://raimannma.github.io/carrot/

**Comment by christianechevarria** [comment]
Hi, just following up on this, the site is back up and functioning. It seems like the gh-pages branch was deleted which made the site unavailable. Feel free to use the TypeScript version but it's currently undergoing major changes and is experimental. 

@raimannma we may want to branch the `typescript` branch again into a `typescript-neat` branch since some of the intermediate NEAT changes will likely make the library unusable (i.e. not converging)

**Comment by christianechevarria** [comment]
Closing this for now, thanks for opening the issue @theWebalyst !
