### ISSUE TITLE
it says network is undefined when i do the .toJSON

### ISSUE THREAD

**Issue by RadiantUwU** [liquidcarrot/carrot#247]
![image](https://user-images.githubusercontent.com/69520693/89999981-3cb73200-dc98-11ea-8b23-badfdcc26908.png)

```javascript
async function trainAI (theinput, times, error, mutationRate) {
	try {
		if (!error) error = 0.05;
		if (!mutationRate) mutationRate = 0.5;
		var trainingSet = theinput;
		for (i = 0; i < times; i++) {
			await network.evolve(trainingSet, {
				mutation: methods.mutation.FFW,
				equal: true,
				error: error,
				elitism: 5,
				mutation_rate: mutationRate
			});
		}
	}
	catch (err) {
		throw err;
	}
}

let exported = network.toJSON(); < error

fs.writeFileSync('./AI.json', exported);
```

**Comment by christianechevarria** [comment]
Hi @RadiantUwU, are you using the pure JS version of the library or the experimental TS version on the `typescript` branch?

If you're using the `network.evolve` in the pure JS version then the problem most likely stems from using the `async await` pattern since `network.evolve` is not actually async (unfortunately, we're working on this in the new TS version)

**Comment by RadiantUwU** [comment]
it was initialised tho
:P

**Comment by raimannma** [comment]
Yes, possible.

But it seems to me that the network variable is not defined the moment you call it.

So it would be good to have your complete code or even just the relevant code where you initialize the network and where you execute toJSON().

Maybe a network variable is defined, but it is not accessible at the moment you call toJSON().

**Comment by radiantgurl** [comment]
im using stuff like im using network variable, but i didnt even globalize it
